### ISSUE TITLE
fail to make pip_pkg

### ISSUE THREAD

**Issue by boboofan** [jackd/pointnet_ops#2]
I tried to compile on my server and failed.
Would you like to help check what went wrong

Environment:
centos-7
cuda-10.1
cudnn-7.6.5
python-3.6.8
tensorflow-2.2.0

make: Circular pointnet_ops/cc/kernels/group.cu <- pointnet_ops/cc/kernels/group.cu.o dependency dropped.
/usr/local/cuda-10.1/bin pointnet_ops/cc/kernels/group.cu -o pointnet_ops/cc/kernels/group.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC
make: execvp: /usr/local/cuda-10.1/bin: Permission denied
make: *** [pointnet_ops/cc/kernels/group.cu.o] Error 127

**Comment by jackd** [comment]
Do you have write access to `pointnet_ops` directory?

**Comment by boboofan** [comment]
Thanks for your response.
I have solved the problem by updating gcc compiler.
